In [1]:
import numpy as np

In [39]:
A = np.array([[2, -1], [1, 1]])
A

array([[ 2, -1],
       [ 1,  1]])

In [42]:

B = np.array([[3, 0]]).T
B

array([[3],
       [0]])

In [43]:
np.linalg.solve(A,B)

array([[ 1.],
       [-1.]])

In [44]:
np.linalg.matrix_rank(A)

2

In [61]:
A.shape

(2, 2)

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.diag(np.array([3, 1, 5]))

array([[3, 0, 0],
       [0, 1, 0],
       [0, 0, 5]])

In [47]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [48]:
np.linalg.inv(A)

array([[ 0.33333333,  0.33333333],
       [-0.33333333,  0.66666667]])

In [49]:
np.linalg.det(A)

2.9999999999999996

In [51]:
#Correlation
def corr(X, Y):
    X_demeaned = X - np.average(X)
    Y_demeaned = Y - np.average(Y)
    
    X_length = np.sqrt(X_demeaned.dot(X_demeaned))
    Y_length = np.sqrt(Y_demeaned.dot(Y_demeaned))
    
    X_Y = X_demeaned.dot(Y_demeaned)
    
    return X_Y/(X_length * Y_length)

X = np.array([99, 80, 79, 75.5, 87.5, 67, 76])
Y = np.array([100, 82.5, 79, 82.5, 91, 67.5, 68])

corr(X, Y)


0.9207408535992782

In [54]:
#Orthogonal projection of v onto u:
def proj(v, u):
    return (u.dot(v)/(u.dot(u)))*u

u = np.array([2, -1, -2])
v = np.array([2, 1, 3])

print(proj(v, u))
print(v - proj(v, u))

[-0.66666667  0.33333333  0.66666667]
[2.66666667 0.66666667 2.33333333]


In [57]:
x = np.array([1, 1, 1])
y = np.array([1, -1, -2])
np.cross(x, y)

array([-1,  3, -2])

In [58]:
def scalar_triple_product(u, v, w):
    return u.dot(np.cross(v, w))

u = np.array([2, 1, 1])
v = np.array([1, -1, 2])
w = np.array([0, -2, 3])
scalar_triple_product(u, v, w)

-3

In [67]:
#Orthonormal basis for null(A) using SVD
import scipy
A = np.array([[2, 1], [8, 1]])
ns = scipy.linalg.null_space(A)
ns

array([], shape=(2, 0), dtype=float64)

In [68]:
#Orthonormal basis for A
cs = scipy.linalg.orth(A)
cs

array([[-0.25492922, -0.96695972],
       [-0.96695972,  0.25492922]])

In [71]:
w, v = np.linalg.eig(A)
print(w)
print(v)

[ 4.37228132 -1.37228132]
[[ 0.38843465 -0.28429885]
 [ 0.92147627  0.95873571]]


In [80]:
np.matmul(np.matmul(v, np.diag(w)), np.linalg.inv(v))

array([[2., 1.],
       [8., 1.]])

In [81]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)
u, s, vh = np.linalg.svd(a, full_matrices=True)
print(u)
print(s)
print(vh)

[[ 2.06336789e-01-0.08270282j  1.35178580e-01-0.11043312j
   1.75292942e-01+0.16262673j -2.88645344e-01-0.0479553j
  -5.74595105e-01+0.08524309j  3.58973214e-04-0.47960634j
  -3.43660559e-01-0.18982869j  1.35077673e-01+0.18380198j
  -5.23036698e-02+0.03122693j]
 [-1.76874507e-01-0.36001668j -1.13640365e-02+0.07326411j
  -5.37806273e-02+0.02038505j -5.15291864e-01-0.31454099j
   1.47905237e-01-0.11600942j  1.29857248e-01-0.13031547j
   1.32414812e-01+0.03605883j  2.94222917e-01-0.53810412j
  -3.16013721e-02+0.02649657j]
 [-2.78984251e-01-0.4984046j  -1.59835747e-01+0.19651977j
  -2.64506520e-01+0.11471596j  1.59871772e-01+0.06523708j
  -2.46678800e-01+0.28999148j  2.18146673e-01-0.1143755j
   2.24238271e-01-0.02724552j -1.51159317e-01+0.18287251j
   3.53519252e-01-0.24237813j]
 [ 8.85702359e-03-0.30324494j  4.29177120e-03-0.43440157j
  -6.87664646e-02-0.07188514j  5.05650035e-01+0.18242869j
   1.47208366e-01-0.1366185j   4.18403191e-02-0.25654034j
  -1.32262281e-01-0.3940991j   6.432970